version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskboard
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "54321:5432"
    volumes:
      - taskboard_db:/var/lib/postgresql/taskboard_data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  taskboard_db:
